sudo: false
language: node_js
node_js:
- '4'
- '5'
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run test
deploy:
  provider: npm
  email: will@worrbase.com
  api_key:
    secure: L1twxyaR7/wdMy7L4BS8KsaO7hYDprxn8edr2nOKxA2t1vh4I/kdiehonmtQW4BS91YUma/n6rvFbZWFx3nsMypMps8RLhKXvjaIIJKENopfCAVNrnZdH1AztoFFhgUyApGyJ7fm9y1ypTkedPFyhGtNOvAMQ9k1E47VFtEHMSI=
  on:
    tags: true
